"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = require("express");
const CourseController_1 = require("../controllers/CourseController");
const CourseRoutes = (0, express_1.Router)();
CourseRoutes.post("/", CourseController_1.CREATE_COURSE);
CourseRoutes.get("/", CourseController_1.LIST_COURSES);
CourseRoutes.post("/discussions/:discussionId/reply", CourseController_1.REPLY_TO_DISCUSSION);
CourseRoutes.get("/:courseId/discussions", CourseController_1.LIST_COURSE_DISCUSSIONS);
CourseRoutes.post("/:courseId/lessons/:lessonId/doubts", CourseController_1.CREATE_DISCUSSION);
CourseRoutes.get("/:courseId/lessons/:lessonId/doubts", CourseController_1.LIST_LESSON_DISCUSSIONS);
CourseRoutes.post("/:courseId/modules", CourseController_1.ADD_MODULE);
CourseRoutes.patch("/:courseId/modules/:moduleId", CourseController_1.UPDATE_MODULE);
CourseRoutes.delete("/:courseId/modules/:moduleId", CourseController_1.DELETE_MODULE);
CourseRoutes.post("/:courseId/modules/:moduleId/lessons", CourseController_1.ADD_LESSON);
CourseRoutes.patch("/:courseId/modules/:moduleId/lessons/:lessonId", CourseController_1.UPDATE_LESSON);
CourseRoutes.delete("/:courseId/modules/:moduleId/lessons/:lessonId", CourseController_1.DELETE_LESSON);
CourseRoutes.get("/:courseId", CourseController_1.GET_COURSE);
CourseRoutes.patch("/:courseId", CourseController_1.UPDATE_COURSE);
CourseRoutes.delete("/:courseId", CourseController_1.DELETE_COURSE);
exports.default = CourseRoutes;
